### ISSUE TITLE
Using afkak with kafka's SSL auth

### ISSUE THREAD

**Issue by tasdomas** [ciena/afkak#103]
Is there a recommended way to connect afkak to a kafka cluster that uses ssl authentication?

**Comment by twm** [comment]
The [`KafkaClient` class](https://afkak.readthedocs.io/en/latest/api.html#kafkaclient-objects) has an `endpoint_factory` parameter that is intended to enable this:

> **endpoint_factory** – Callable which accepts reactor, host and port arguments. It must return a twisted.internet.interfaces.IStreamClientEndpoint.
> 
> Afkak does not apply a timeout to connection attempts because most endpoints include timeout logic. For example, the default of [`HostnameEndpoint`](https://twistedmatrix.com/documents/current/api/twisted.internet.endpoints.HostnameEndpoint.html) applies a 30-second timeout. If an endpoint doesn’t support timeouts you may need to wrap it to do so.

You can provide one that returns an endpoint with the appropriate TLS configuration. Something like this (untested):

```py
from twisted.internet.ssl import optionsForClientTLS
from twisted.internet.endpoints import HostnamEndpoint, wrapClientTLS

def tls_client_endpoint(reactor, host, port):
    return wapClientTLS(
        optionsForClientTLS(host),
        HostnameEndpoint(reactor, host, port),
    )

client = KafkaClient(..., endpoint_factory=tls_client_endpoint)
```

[`optionsForClientTLS()`](https://twistedmatrix.com/documents/current/api/twisted.internet.ssl.html#optionsForClientTLS) lets you configure trust roots, client certificates, etc.

This isn't well-advertised because I haven't had opportunity to write an integration test for it. Please report back if it works for you!

**Comment by tasdomas** [comment]
That worked! Thanks!
